version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: game_store_db
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - /path/to/game_store/postgres/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks:
            - game_store_api-network
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - 8080:80
        depends_on:
            - postgres
        networks:
            - game_store_api-network
networks:
    game_store_api-network: